"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.core.management.utils import get_random_secret_key

SECRET_KEY = get_random_secret_key()
# Paths
BASE_DIR = Path(__file__).resolve().parent       # => .../backend
PROJECT_ROOT = BASE_DIR.parent                   # => repo root (has templates/, frontend/)

# Debug
DEBUG = True   # switch to False in production
ALLOWED_HOSTS = ["*"]  # tighten this in production

# Installed apps
INSTALLED_APPS = [
    # Core Django apps (required)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",

    # Static files
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",

    # Third-party
    "django_vite",

    # Your apps
    "sketch_api",
]

# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Templates
TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [PROJECT_ROOT / "backend" / "templates"],   # repo-root/templates/index.html
    "APP_DIRS": True,
    "OPTIONS": {"context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
    ]},
}]

# WSGI
WSGI_APPLICATION = "backend.wsgi.application"

# Static
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only include dist/ if it exists (so you don’t get warnings in dev)
dist_path = PROJECT_ROOT / "frontend" / "dist"
STATICFILES_DIRS = [dist_path] if dist_path.exists() else []

ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"

# django-vite
DJANGO_VITE = {
    "default": {
        "dev_mode": True,                 # True in dev, False in prod
        "dev_server_host": "localhost",   # or "127.0.0.1"
        "dev_server_port": 5173,
        "manifest_path": dist_path / ".vite" / "manifest.json",
        "static_url_prefix": "",          # prevent /static prefix in dev
    }
}

# Some django-vite versions also require these env-style flags:
DJANGO_VITE_DEV_MODE = True
DJANGO_VITE_DEV_SERVER_HOST = "localhost"
DJANGO_VITE_DEV_SERVER_PORT = 5173

# Production-only: enable optimized static storage
# if not DEBUG:
#     STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"